#!/bin/bash
#PBS -N fit_run_combPSFs
#PBS -o /home/xuheng.ding/Astro/my_code/projects/2022_CEERS_checkup/real_analysis/model_JWST_stage3_Masafusa/pbs/
#PBS -e /home/xuheng.ding/Astro/my_code/projects/2022_CEERS_checkup/real_analysis/model_JWST_stage3_Masafusa/pbs/
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:50:00
#PBS -l mem=200mb
#PBS -J 1-1416:1
#PBS -u xuheng.ding
#PBS -m ae
#PBS -V
#PBS -q tiny

cd /home/xuheng.ding/Astro/my_code/projects/2022_CEERS_checkup/real_analysis/model_JWST_stage3_Masafusa/
python 2_fit_DP_with_combPSFs.py $PBS_ARRAY_INDEX

