#!/bin/bash
#PBS -N Galight_Liu19_type2
#PBS -o /home/xuheng.ding/Astro/my_code/projects/2022_fit_Liu19_catalog/pbs/
#PBS -e /home/xuheng.ding/Astro/my_code/projects/2022_fit_Liu19_catalog/pbs/
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:50:00
#PBS -l mem=200mb
#PBS -J 1-552:1
#PBS -u xuheng.ding
#PBS -m ae
#PBS -V
#PBS -q tiny

cd /home/xuheng.ding/Astro/my_code/projects/2022_fit_Liu19_catalog/
python 5_fit_2023newBLAGN_5band_onidark.py $PBS_ARRAY_INDEX
