#!/bin/bash
#PBS -N fit_run_HST
#PBS -o /home/xuheng.ding/Astro/my_code/projects/2022_CEERS_checkup/real_analysis/model_HST_material/pbs
#PBS -e /home/xuheng.ding/Astro/my_code/projects/2022_CEERS_checkup/real_analysis/model_HST_material/pbs
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:50:00
#PBS -l mem=200mb
#PBS -J 1-3378:1
#PBS -u xuheng.ding
#PBS -m ae
#PBS -V
#PBS -q tiny

cd /home/xuheng.ding/Astro/my_code/projects/2022_CEERS_checkup/real_analysis/model_HST_material/
python 1_fit_5band_onidark.py $PBS_ARRAY_INDEX
