#!/bin/bash
#PBS -N sed_2d
#PBS -o /home/xuheng.ding/Astro/my_code/projects/2022_CEERS_checkup/real_analysis/2d_SED_AEGIS_630/pbs/
#PBS -e /home/xuheng.ding/Astro/my_code/projects/2022_CEERS_checkup/real_analysis/2d_SED_AEGIS_630/pbs/
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:50:00
#PBS -l mem=200mb
#PBS -J 1-2304:1
#PBS -u xuheng.ding
#PBS -m ae
#PBS -V
#PBS -q tiny

cd /home/xuheng.ding/Astro/my_code/projects/2022_CEERS_checkup/real_analysis/2d_SED_AEGIS_630/
source activate gsf
python 2_sed_2Dmap_idark.py $PBS_ARRAY_INDEX 1
