#!/bin/bash
#PBS -N fit_run_JWST
#PBS -o /home/xuheng.ding/Astro/my_code/projects/2022_COSMOSweb/pbs/
#PBS -e /home/xuheng.ding/Astro/my_code/projects/2022_COSMOSweb/pbs/
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:50:00
#PBS -l mem=200mb
#PBS -J 6000-12001:1
#PBS -u xuheng.ding
#PBS -m ae
#PBS -V
#PBS -q tiny

cd /home/xuheng.ding/Astro/my_code/projects/2022_COSMOSweb
python 1_run_fit_onidark.py $PBS_ARRAY_INDEX
