#!/bin/bash
#PBS -N sed_simulation
#PBS -o /home/xuheng.ding/Astro/my_code/projects/2022_JWST_QSOz6/simulation_SED/pbs/
#PBS -e /home/xuheng.ding/Astro/my_code/projects/2022_JWST_QSOz6/simulation_SED/pbs/
#PBS -l nodes=1:ppn=1
#PBS -l walltime=03:50:00
#PBS -l mem=200mb
#PBS -J 1-2000:1
#PBS -u xuheng.ding
#PBS -m ae
#PBS -V
#PBS -q tiny

cd /home/xuheng.ding/Astro/my_code/projects/2022_JWST_QSOz6/simulation_SED/
source activate gsf
python run_simulation_idark_prior1.py $PBS_ARRAY_INDEX 0 1 1